nameco_user_scheduler:
    resource: "@NamecoUserSchedulerBundle/Controller/"
    type:     annotation
    prefix:   /

nameco_user_scheduler_ajax:
    resource: "@NamecoUserSchedulerBundle/Resources/config/routing.yml"

nameco_security:
    resource: "@NamecoSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

nameco_admin_user:
    resource: "@NamecoAdminUserBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
