jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Nameco\Admin\UserBundle\Entity\User:   sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main_provider:
          chain:
            providers: [user_db, admin]
        admin:
          memory:
            users:
              admin:  { password: namecoadmin, roles: [ 'ROLE_ADMIN' ] }
        user_db:
          entity:  { class: Nameco\Admin\UserBundle\Entity\User, property: username }
        

    firewalls:
        login:
            pattern:  ^/(login$|css|js|images)
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /login
            anonymous: false
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
